Makefile: Let users chose to fail on first error
By default the top level makefile was not failing and stopping when
a component could not be built. Instead it was printing a warning
and continuing with whatever it could do.

With this patch it is possible for the user to change this behaviour
by setting the environment variable BSIM_BUILD_FAIL_ASAP.
When set, make will fail as soon as any component fails.

Signed-off-by: Alberto Escolar Piedras <alpi@oticon.com>

diff --git a/common/Makefile b/common/Makefile
--- a/common/Makefile
+++ b/common/Makefile
@@ -52,7 +52,17 @@ include ${DEPENDFILES}
 
 $(COMPONENTS): | ${BSIM_OUT_PATH} ${BSIM_OUT_PATH}/bin/ ${BSIM_OUT_PATH}/lib/ ${BSIM_OUT_PATH}/results/
 	@if [ ! -d "${BSIM_OUT_PATH}/components/$@" ];then mkdir -p  ${BSIM_OUT_PATH}/components/$@ ; fi #let's create the output mirror directory of each component if it doesnt exist 
-	@export COMPONENT_OUTPUT_DIR=$(abspath ${BSIM_OUT_PATH}/components/$@) ; ${MAKE} --no-builtin-rules --warn-undefined-variables -C components/$@; ( [ $$? -ne 0 ] && echo "*** NOTE: $@ could NOT be built, continuing ***" ); true
+	@export COMPONENT_OUTPUT_DIR=$(abspath ${BSIM_OUT_PATH}/components/$@) ; ${MAKE} --no-builtin-rules --warn-undefined-variables -C components/$@; \
+	( if [ $$? -ne 0 ]; then \
+	  echo -n "*** NOTE: $@ could NOT be built, " ;\
+	  if [ -z $$BSIM_BUILD_FAIL_ASAP ]; then \
+	   echo "continuing ***" ;\
+	   true; \
+	  else \
+	   echo "aborting ***" ;\
+	   false; \
+	  fi; \
+	fi; )
 
 ${DEPENDFILES}:
 	$(warning $@ does not exist. Either you have a left over component folder or you forgot to add a depend file to a new component, either way please fix it (remove the empty component or create a proper Depend file) )
